# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.srcs/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0.xci
# IP: The module: 'axi_ethernetlite_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ethernetlite_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ethernetlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ethernetlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ethernetlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.srcs/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0.xci
# IP: The module: 'axi_ethernetlite_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ethernetlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ethernetlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ethernetlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ethernetlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
