TARGET = ./build/quant 
LIBS=-lm -lstdc++
CC=g++
CFLAGS= \
-O3 \
-Wall \
-Wno-unused-function \
-Wno-strict-aliasing \
-Wno-format-overflow \
-fpermissive \
-fno-strict-aliasing \
-I.

OBJ = ./apps/llm/gguf/quant.o ./apps/llm/gguf/gguf.o ./apps/llm/gguf/zuf.o

%.o: %.cpp
	$(CC) $(CFLAGS) -DQUANTIZER -c -o $@ $<

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

$(TARGET) : $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

all: $(TARGET) 

clean:
	rm -f $(OBJ) $(TARGET) 
