# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.runs/synth_1/main.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 4
set_msg_config  -id {17-179}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.cache/wt [current_project]
set_property parent.project_path /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/platform/Xilinx/CCD_SYNC.v
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/platform/Xilinx/DPRAM.v
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/platform/Xilinx/DPRAM_BE.v
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/platform/Xilinx/DPRAM_DUAL_CLOCK.v
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/platform/Xilinx/FP32_ADDSUB.v
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/platform/Xilinx/FP32_MUL.v
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/platform/Xilinx/SHIFT.v
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/platform/Xilinx/SPRAM.v
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/platform/Xilinx/SPRAM_BE.v
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/platform/Xilinx/SYNC_LATCH.v
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/riscv/xilinx_jtag/riscv.v
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/main.v
}
read_vhdl -library xil_defaultlib {
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/adder.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/config.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/ztachip_pkg.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/afifo.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/afifo2.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/alu/alu.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/arbiter.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_apb_bridge.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_merge.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_merge_read.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_merge_write.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_ram_read.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_ram_write.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_read.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_resize_read.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_resize_write.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_split.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_split_read.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_split_write.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_stream_read.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_stream_write.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/axi/axi_write.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/top/axilite.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/peripherals/camera.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/top/cell.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/pcore/core.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/top/ddr_rx.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/top/ddr_tx.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/delay.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/delayi.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/delayv.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/dp/dp.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/dp/dp_core.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/dp/dp_fetch.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/dp/dp_fifo.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/dp/dp_gen.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/dp/dp_gen_core.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/dp/dp_sink.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/dp/dp_source.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/peripherals/ethlite.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/fpu/falu.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/fpu/falu2.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/fpu/falu_core.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/fifo.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/fifow.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/fpu/fp12.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/fpu/fp2int.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/fpu/fp_floor.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/fpu/fpmax.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/fpu/fpu.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/peripherals/gpio.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/ialu/ialu.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/pcore/instr.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/pcore/instr_decoder2.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/pcore/instr_dispatch2.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/pcore/instr_fetch.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/ialu/iregister_file.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/ialu/iregister_ram.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/multiplier.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/pcore/pcore.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/ram2r1w.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/ramw.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/ramw2.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/pcore/register_bank.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/pcore/register_file.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/pcore/rom.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/shifter.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/util/shifter_l.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/soc_base.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/top/sram.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/top/sram_core.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/pcore/stream.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/tcm.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/peripherals/time.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/peripherals/uart.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/soc/peripherals/vga.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/pcore/xregister_file.vhd
  /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/src/top/ztachip.vhd
}
read_ip -quiet /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.srcs/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0.xci
set_property used_in_implementation false [get_files -all /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0.xdc]
set_property used_in_implementation false [get_files -all /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/axi_ethernetlite_0/axi_ethernetlite_0_ooc.xdc]

read_ip -quiet /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.srcs/sources_1/ip/float_addsub/float_addsub.xci
set_property used_in_implementation false [get_files -all /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/float_addsub/float_addsub_ooc.xdc]

read_ip -quiet /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.srcs/sources_1/ip/float_mul/float_mul.xci
set_property used_in_implementation false [get_files -all /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/float_mul/float_mul_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/main.xdc
set_property used_in_implementation false [get_files /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/main.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top main -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
