# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.srcs/sources_1/ip/float_addsub/float_addsub.xci
# IP: The module: 'float_addsub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/float_addsub/float_addsub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_addsub'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.srcs/sources_1/ip/float_addsub/float_addsub.xci
# IP: The module: 'float_addsub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/tsmc/6a3f28f3-1a75-4d55-baf2-a6aa8be84a59/kwc/100t/ztachip/HW/examples/GHRD/ztachip.gen/sources_1/ip/float_addsub/float_addsub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'float_addsub'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
